nginx:
  image: "nginx:latest"
  links:
    - registry
  ports:
    - "9443:443"
  volumes:
    - "./nginx/nginx.conf:/etc/nginx/conf.d/docker-registry.conf:ro"
    - "./nginx/docker-registry.key:/etc/nginx/docker-registry.key:ro"
    - "./nginx/docker-registry.crt:/etc/nginx/docker-registry.crt:ro"
    - "./nginx/docker-registry.conf:/etc/nginx/docker-registry.conf:ro"
    - "./nginx/docker-registry.htpasswd:/etc/nginx/docker-registry.htpasswd:ro"
  restart: always
registry:
  build: ./docker-registry
  environment:
    CACHE_REDIS_HOST: redis
    CACHE_REDIS_PORT: 6379
    SEARCH_BACKEND: sqlalchemy
    SETTINGS_FLAVOR: local
    SQLALCHEMY_INDEX_DATABASE: "mysql://root:mysql@mysql:3306/registry"
    STORAGE_PATH: /var/docker-registry-storage
  restart: always
  command: apt-get install python-mysqldb
  links:
    - redis
    - mysql
  volumes:
    - "/var/docker-registry-storage:/var/docker-registry-storage"
redis:
  image: "redis:latest"
  restart: always
mysql:
  environment:
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_DATABASE: registry
  image: "mysql:latest"
  restart: always
